[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
anvil = "http://127.0.0.1:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
